In [6]:
import warnings
from IPython.core.interactiveshell import InteractiveShell
from IPython.display import display, Markdown, HTML, Javascript
from tqdm import tqdm
import geopandas as gpd
import pandas as pd


def alert(message='Loop completed!'):
    # Check if the system supports 'say' and notifications
    os.system(f'osascript -e \'display notification "{message}" with title "Notification"\'')
    # Speak the alert
    os.system(f'say "{message}"')        
        
InteractiveShell.ast_node_interactivity = "all"
warnings.filterwarnings("ignore")
tqdm.pandas()

### Define Ballotpedia API lookup & processing functions
Caches and retrieves Ballotpedia geographic data for a given latitude/longitude. Uses polite rate limiting and request headers. Function has a 100,000 item cache to avoid duplicate API calls.

Functions to transform raw API election data into a structured format:

Process ballot measures and candidate information
Calculate decision metrics (number of races and options)
Format final output as a pandas DataFrame with location data

In [7]:
import requests
import pandas as pd
from functools import lru_cache
from typing import Dict, List, Optional
from collections import defaultdict

# Define Ballotpedia API lookup
@lru_cache(maxsize=100_000)
def get_ballotpedia_data_rigorous(lat, lng, rate_limit=2):
    url = "https://api4.ballotpedia.org/myvote_redistricting_with_historical"
    params = {
        'long': str(lng),
        'lat': str(lat),
        'include_volunteer': 'true'
    }
    headers = {
        'Accept': 'application/json',
        'Content-Type': 'application/json',
        'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/127.0.0.0 Safari/537.36',
        'Referer': 'https://sblv3.ballotpedia.org/',
        'Origin': 'https://sblv3.ballotpedia.org'
    }
    
    response = requests.get(url, params=params, headers=headers)

    # Rate limit
    time.sleep(rate_limit)
    
    if response.json().get('message') == 'Forbidden':
        raise PermissionError


    # print(response.json())
    return response.json()


# Define processing functions
def extract_election_data(api_response: Dict) -> List[Dict]:
    return api_response.get('data', {}).get('elections', [])


#Process ballot measures and candidate information
def process_ballot_measure(measure: Dict, common_data: Dict) -> Dict:
    return {
        **common_data,
        'race_type': 'Ballot Measure',
        'office.name': measure['name'],
        'office.type': 'Ballot Measure',
        'office.level': common_data['district_type'],
        'office.branch': 'N/A',
        'number_of_seats': 1,
        'person.name': 'Yes/No Question',
        'person.url': None,
        'party_affiliation': None,
        'status': 'On the Ballot',
        'is_incumbent': False,
        'running_mate.name': None,
        'measure_id': measure['id'],
        'measure_district_type': measure['district_type']
    }

def process_candidate(candidate: Dict, race: Dict, common_data: Dict) -> Dict:
    office = race['office']
    return {
        **common_data,
        'race_type': 'Candidate',
        'office.name': office['name'],
        'office.type': office['type'],
        'office.level': office['level'],
        'office.branch': office['branch'],
        'number_of_seats': race['number_of_seats'],
        'person.name': candidate['person']['name'],
        'person.url': candidate['person']['url'],
        'party_affiliation': candidate['party_affiliation'],
        'status': candidate['status'],
        'is_incumbent': candidate['is_incumbent'],
        'running_mate.name': candidate['running_mate']['name'] if candidate.get('running_mate') else None,
        'measure_id': None,
        'measure_district_type': None
    }

def process_district(district: Dict, election_date: str) -> List[Dict]:
    common_data = {
        'election_date': election_date,
        'district_name': district['name'],
        'district_type': district['type']
    }
    
    ballot_measures = [process_ballot_measure(measure, common_data) for measure in district.get('ballot_measures') or []]
    candidates = [process_candidate(candidate, race, common_data) 
                  for race in district.get('races')  or []
                  for candidate in race['candidates']]
    
    return ballot_measures + candidates

#Calculate decision metrics (number of races and options)
def calculate_decision_metrics(df: pd.DataFrame) -> pd.DataFrame:
    def count_decisions_and_options(group):
        decisions = defaultdict(int)
        for _, row in group.iterrows():
            if row['race_type'] == 'Ballot Measure':
                decisions[row['office.name']] = 2  # Yes/No options
            else:
                decisions[row['office.name']] += 1
        
        unique_decisions = len(decisions)
        total_options = sum(decisions.values())
        
        group['unique_decisions'] = unique_decisions
        group['total_options'] = total_options
        return group

    return df.groupby(['district_name', 'district_type']).apply(count_decisions_and_options).reset_index(drop=True)

    
#Format final output as a pandas DataFrame with location data
def process_api_response(api_response: Dict, lat: float, lng: float) -> Optional[pd.DataFrame]:
    if not api_response:
        return None
        
    elections = extract_election_data(api_response)
    if not elections:
        return None
    
    processed_data = [
        item for election in elections
        for district in election['districts']
        for item in process_district(district, election['date'])
    ]
    
    df = pd.DataFrame(processed_data)
    df['group_id'] = df.groupby(['district_name', 'district_type']).ngroup()
    df['lat'], df['lng'] = lat, lng
    
    df = calculate_decision_metrics(df)
    
    return df

### Set up dataframe

In [8]:
import json

#Read the areas.shp shapefile and find the center_lat value that becomes the 'latlng' column
area_df = gpd.read_file('data/raw/areas.shp')
area_df['latlng'] = area_df.lookup_lat.fillna(area_df.center_lat).apply(eval)
area_df = area_df.rename(columns={'intersecti': 'intersection_id'})
area_df['district'] = area_df.district.str.replace('00', '01')
#AZspecific filtering by 'state id' 
az_area_df = area_df[area_df['state_id'] == 'AZ']
az_area_df 

# Define the desired column names
column_names = ['zip', 'state', 'district', 'county', 'lat', 'lng', 'response']

#running this cell to CREATE an empty result_df 
# Create an empty DataFrame with the specified columns
result_df = pd.DataFrame(columns=column_names)


#we have no idea 
response_lookup = dict(result_df
                       .drop_duplicates(['zip', 'lat', 'lng'])
                       .set_index(['zip', 'lat', 'lng'])
                       .response.apply(json.loads))
response_lookup.update(dict(result_df
                            .drop_duplicates(['zip', 'county', 'district'])
                            .set_index(['zip', 'county', 'district'])
                            .response.apply(json.loads)))

,intersection_id,zip,county,district,population,state,state_id,center_lat,lookup_lat,best_width,link,geometry,latlng
7459,8131,85333,Yuma,09,501.0,Arizona,AZ,"(32.921822005682955, -113.43842065650553)","(32.921822005682955, -113.43842065650553)",18843.705658,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1598560.556 1262192.214, -1598569.3...","(32.921822005682955, -113.43842065650553)"
7460,8133,85364,Yuma,09,72225.0,Arizona,AZ,"(32.71447792615716, -114.59443219418046)","(32.71447792615716, -114.59443219418046)",2745.769737,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((-1723351.431 1242984.374, -172...","(32.71447792615716, -114.59443219418046)"
7461,8134,85364,Yuma,07,72225.0,Arizona,AZ,"(32.700761056908796, -114.6790922837226)","(32.70469, -114.65664)",5737.739525,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1736919.04 1238304.738, -1736909.98...","(32.70469, -114.65664)"
7462,8135,85364,Yuma,25,72225.0,Arizona,AZ,"(32.73888145307751, -114.70208682910409)","(32.73888145307751, -114.70208682910409)",518.269886,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((-1729618.755 1244548.468, -172...","(32.73888145307751, -114.70208682910409)"
7463,8136,85365,Yuma,09,49699.0,Arizona,AZ,"(33.08289818159969, -114.12552921403879)","(33.07067, -114.13801)",44598.032590,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1731183.982 1237122.048, -1731060.8...","(33.07067, -114.13801)"
...,...,...,...,...,...,...,...,...,...,...,...,...,...
48629,52859,86547,Apache,02,1040.0,Arizona,AZ,"(36.527557356440724, -109.4602850301337)","(36.52759, -109.46019)",14165.229360,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1203091.333 1582760.664, -1203073.6...","(36.52759, -109.46019)"
52447,57041,86514,San Juan,03,3367.0,Arizona,AZ,"(37.05063360118225, -109.19017149680822)","(37.05063360118225, -109.19017149680822)",11085.947587,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1150265.516 1629999.619, -1150659.6...","(37.05063360118225, -109.19017149680822)"
52460,57059,86044,San Juan,02,3149.0,Arizona,AZ,"(37.15872010360266, -110.92905825511951)","(37.15872010360266, -110.92905825511951)",730.892388,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((-1306081.016 1672202.098, -130...","(37.15872010360266, -110.92905825511951)"
52461,57060,86044,San Juan,02,3149.0,Arizona,AZ,"(37.002713381924515, -110.87524107473315)","(37.002713381924515, -110.87524107473315)",37.699200,https://edbltn.github.io/show-me-the-ballot/da...,"MULTIPOLYGON (((-1270711.186 1647415.589, -127...","(37.002713381924515, -110.87524107473315)"
52462,57061,86044,San Juan,03,3149.0,Arizona,AZ,"(37.08954149721607, -110.74490281594383)","(37.08954149721607, -110.74490281594383)",18269.919643,https://edbltn.github.io/show-me-the-ballot/da...,"POLYGON ((-1271063.398 1647583.681, -1271324.8...","(37.08954149721607, -110.74490281594383)"

### Define main scraping and processing loop
Processes and accumulates data for each geographic point through the Ballotpedia API

In [78]:
import os
import time

# Pandas(Index=7459, intersection_id=8131, zip='85333', county='Yuma', district='09', population=501.0, state='Arizona', 
#        state_id='AZ', center_lat='(32.921822005682955, -113.43842065650553)', 
#        lookup_lat='(32.921822005682955, -113.43842065650553)', best_width=18843.70565791754, 
#        link='https://edbltn.github.io/show-me-the-ballot/data/processed/85333.html', 
#        geometry=<POLYGON ((-1598560.556 1262192.214, -1598569.343 1262144.574, -1598575.741 ...>, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
# Define the desired column names
column_names = ['intersection_id', 'zip', 'county', 'district', 'population', 'state', 'state_id', 'center_lat', 'lookup_lat', 'best_width', 'link', 'geometry', 'latlng', 'response']

def process_dataframe(df):
    all_results = []
    
    for row in tqdm(df.itertuples(), total=len(df), desc="Processing rows"):

        lat, lng = row.latlng
        key1 = (str(int(row.zip)), str(lat)[:12], str(lng)[:12])
        key2 = (f'{int(row.zip):05}', str(lat)[:12], str(lng)[:12])
        key3 = (str(int(row.zip)), row.county, row.district)
        key4 = (str(int(row.zip)), row.county, None)
        key5 = (str(int(row.zip)), row.county, 'ne')
        key6 = (str(int(row.zip)), row.county, '00')
        key7 = (str(int(row.zip)), row.county, '01')
        for key_ in [key1, key2, key3, key4, key5, key6, key7]:
            if key_ in response_lookup:
                break
        key = key_
        if key in response_lookup:
            response = response_lookup[key]
        else:
            response = None
            for i in range(3):
                try:
                    response = get_ballotpedia_data_rigorous(lat, lng, rate_limit=0.2)
                    # if response['data']['districts'] is not None:
                    #     response['data']['districts'][0]
                    break
                except PermissionError:
                    if i == 0:
                        print('PermissionError:', lat, lng, row.state, row.county)
                    os.system('say "beep"')  # Uses system text-to-speech to make a sound
                    time.sleep(3**(i))
                    continue
                except Exception as e:
                    print('Exception:', e, lat, lng, row.state, row.county)
                    #print(response)
                    print(e)
                    time.sleep(2**(i))
                    continue
        #NOTE: we're not using the decision_metrics method here; to be used later
        response_df = process_api_response(response, lat, lng)


#for debugging: 
        # if response_df is None:
        #     display(row.zip)
        #     display(row.county)
        #     display(row.district)
        #     continue
        # else:
        #     response_lookup[row.zip, row.county, row.district] = response

#commenting the below to prevent duplication  
        # response_df['response'] = json.dumps(response)
        # response_df['intersection_id'] = row.intersection_id
        # response_df['district'] = row.district
        # response_df['county'] = row.county
        # response_df['state'] = row.state
        # response_df['zip'] = row.zip
        # response_df['geometry'] = row.geometry

#using the 'row' in pandas 
        #result_df = pd.DataFrame(columns=column_names)
        #pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)[source]
        #df.loc[len(df)] = new_person

        # print(row)
        # faulty row???  start_df = pd.DataFrame(row, columns=column_names)
        start_df = pd.DataFrame(columns=column_names)

        # row.drop('index')
        start_df.loc[len(start_df)] = row
        
        #del row['Index']
        print(dir(row))
        start_df['response'] = json.dumps(response)
        
        print(start_df)
        results = start_df.to_dict(orient='records')

        # results = row
        
        all_results.extend(results)
        
    # return all_results (failed attempt 10/16)
        
    return pd.DataFrame(all_results)

Intermediate step

In [94]:
import os
import time

# Pandas(Index=7459, intersection_id=8131, zip='85333', county='Yuma', district='09', population=501.0, state='Arizona', 
#        state_id='AZ', center_lat='(32.921822005682955, -113.43842065650553)', 
#        lookup_lat='(32.921822005682955, -113.43842065650553)', best_width=18843.70565791754, 
#        link='https://edbltn.github.io/show-me-the-ballot/data/processed/85333.html', 
#        geometry=<POLYGON ((-1598560.556 1262192.214, -1598569.343 1262144.574, -1598575.741 ...>, 
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
# Define the desired column names
column_names = ['intersection_id', 'zip', 'county', 'district', 'population', 'state', 'state_id', 'center_lat', 'lookup_lat', 'best_width', 'link', 'geometry', 'latlng', 'response']

def process_dataframe(df):
    all_results = []
    
    for row in tqdm(df.itertuples(), total=len(df), desc="Processing rows"):

        lat, lng = row.latlng
        for i in range(3):
            try:
                response = get_ballotpedia_data_rigorous(lat, lng, rate_limit=0.2)
                # if response['data']['districts'] is not None:
                #     response['data']['districts'][0]
                break
            except PermissionError:
                if i == 0:
                    print('PermissionError:', lat, lng, row.state, row.county)
                os.system('say "beep"')  # Uses system text-to-speech to make a sound
                time.sleep(3**(i))
                continue
            except Exception as e:
                print('Exception:', e, lat, lng, row.state, row.county)
                #print(response)
                print(e)
                time.sleep(2**(i))
                continue
        #NOTE: we're not using the decision_metrics method here; to be used later
        response_df = process_api_response(response, lat, lng)


#using the 'row' in pandas 
        #result_df = pd.DataFrame(columns=column_names)
        #pandas.DataFrame(data=None, index=None, columns=None, dtype=None, copy=None)[source]
        #df.loc[len(df)] = new_person

        # print(row)
        # faulty row???  start_df = pd.DataFrame(row, columns=column_names)

        # df = pd.DataFrame.from_records([person_data], columns=person_data._fields)
        
        # start_df = pd.DataFrame(columns=column_names)
        
        start_df = pd.DataFrame.from_records([row], columns=row._fields)
        

        # row.drop('index')
        # start_df.loc[len(start_df)] = row

        # start_df['county'] = row.county
        # start_df[0] = row.county
        
        #del row['Index']
        # print(dir(row))
        start_df['response'] = json.dumps(response)
        
        print(start_df)
        # results = start_df.to_dict(orient='records')

        # results = row
        #extend is a form of concatenation 
        all_results.extend(start_df)
        
        
    return pd.DataFrame(all_results)

CLEAN VERSION

In [101]:
import os
import time
                                                                                                                                                                                                                                                                                                                                                                                                                                                          
# Define the desired column names
column_names = ['intersection_id', 'zip', 'county', 'district', 'population', 'state', 'state_id', 'center_lat', 'lookup_lat', 'best_width', 'link', 'geometry', 'latlng', 'response']

def process_dataframe(df):
    all_results = pd.DataFrame()
    
    for row in tqdm(df.itertuples(), total=len(df), desc="Processing rows"):

        lat, lng = row.latlng
        for i in range(3):
            try:
                response = get_ballotpedia_data_rigorous(lat, lng, rate_limit=0.2)
                break
            except PermissionError:
                if i == 0:
                    print('PermissionError:', lat, lng, row.state, row.county)
                os.system('say "beep"')  # Uses system text-to-speech to make a sound
                time.sleep(3**(i))
                continue
            except Exception as e:
                print('Exception:', e, lat, lng, row.state, row.county)
                print(e)
                time.sleep(2**(i))
                continue
        #NOTE: we're not using the decision_metrics method here; to be used later
        response_df = process_api_response(response, lat, lng)
        
        row_df = pd.DataFrame.from_records([row], columns=row._fields)
        row_df['response'] = json.dumps(response)
        
        print(row_df)
        all_results.append(row_df)
        
    # return pd.DataFrame(all_results)
    return all_results

In [ ]:
#TO DO Oct 16 : brand new dataframe lololol with row.intersection, districit, county, state, zip and response for raw JSON data

In [ ]:
### Do the scraping

In [97]:
result_df = process_dataframe(az_area_df)

Processing rows: 100%|███████████████████████████████████████| 666/666 [00:03<00:00, 201.94it/s]

In [98]:
result_df.head(10)

                 0
0            Index
1  intersection_id
2              zip
3           county
4         district
5       population
6            state
7         state_id
8       center_lat
9       lookup_lat

In [62]:
result_df = process_dataframe(az_area_df)

Processing rows:   2%|▋                                        | 12/666 [00:00<00:10, 60.02it/s]

   intersection_id   zip county district population  state state_id  \
0             7459  8131  85333     Yuma         09  501.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.921822005682955, -113.43842065650553)

                                  best_width          link  \
0  (32.921822005682955, -113.43842065650553)  18843.705658

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1598560.5563676076 1262192.21407036...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7460  8133  85364     Yuma         09  72225.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.71447792615716, -114.59443219418046)

                                 best_width         link  \
0  (32.71447792615716, -114.59443219418046)  2745.769737

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1723351.4309271856 1242984.37...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7461  8134  85364     Yuma         07  72225.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.700761056908796, -114.6790922837226)

               best_width         link  \
0  (32.70469, -114.65664)  5737.739525

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1736919.0400919488 1238304.73762323...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7462  8135  85364     Yuma         25  72225.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.73888145307751, -114.70208682910409)

                                 best_width        link  \
0  (32.73888145307751, -114.70208682910409)  518.269886

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1729618.7549795413 1244548.46...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7463  8136  85365     Yuma         09  49699.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.08289818159969, -114.12552921403879)

               best_width         link  \
0  (33.07067, -114.13801)  44598.03259

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1731183.9821599824 1237122.04793885...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7464  8137  85365     Yuma         07  49699.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.580869503607225, -114.63947864440118)

                                  best_width         link  \
0  (32.580869503607225, -114.63947864440118)  6213.487897

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1717273.6607070412 1229369.03...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7465  8138  85365     Yuma         25  49699.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.871786644470916, -114.50337999112986)

                                  best_width        link  \
0  (32.871786644470916, -114.50337999112986)  938.804411

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1706353.1105403053 1266584.69...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population  state state_id  \
0             7466  8139  85347     Yuma         09  653.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.78597739943264, -113.80689880345483)

               best_width          link  \
0  (32.78612, -113.80633)  12460.457028

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1677775.4650853176 1239255.27125045...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7467  8141  85367     Yuma         09  20326.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.66128847625656, -114.39419973310885)

               best_width         link  \
0  (32.66082, -114.39361)  7690.996769

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1713795.077701737 1230024.190965097...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7468  8142  85367     Yuma         07  20326.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.621680760982294, -114.3436856008294)

                                 best_width        link  \
0  (32.621680760982294, -114.3436856008294)  419.763028

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1699710.3935059463 1225539.45650455...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7469  8143  85349     Yuma         07  18838.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.47998396394357, -114.69639994362124)

               best_width         link  \
0  (32.47983, -114.69647)  4809.711676

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1741668.9670334235 1217239.34...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7470  8144  85350     Yuma         09  18838.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.57912820570843, -114.62552549187151)

                                 best_width         link  \
0  (32.57912820570843, -114.62552549187151)  1542.606882

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1726829.1352393175 1230502.93649361...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7471  8145  85350     Yuma         07  18838.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.56598800467884, -114.71105060963222)

               best_width          link  \
0  (32.51904, -114.77977)  11596.409852

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1745399.389414962 1228073.477...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population  state state_id  \
0             7472  8146  85352     Yuma         09  653.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.692488243428144, -113.89311933297796)

              best_width         link  \
0  (32.69118, -113.8963)  5615.438076

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1670929.0750224176 1223738.59012567...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population  state state_id  \
0             7473  8147  85352     Yuma         07  653.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.65498192874027, -113.98417508797134)

                                 best_width         link  \
0  (32.65498192874027, -113.98417508797134)  1215.627068

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1651483.0845251575 1222807.13...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7474  8148  85336     Yuma         07  18838.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (32.51851383954928, -114.7788072225669)

                                best_width         link  \
0  (32.51851383954928, -114.7788072225669)  1830.057656

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1743394.0057763704 1221016.24...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7475  8149  85356     Yuma         09  4220.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.693325809549826, -114.18720968635475)

              best_width          link  \
0  (32.68933, -114.1852)  14665.375872

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1703202.1721985627 1240775.45038644...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7476  8150  85356     Yuma         07  4220.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.61009955255812, -114.14457503953314)

                                 best_width         link  \
0  (32.61009955255812, -114.14457503953314)  2909.894764

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1671190.5910461862 1222330.12...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7571  8256  85138    Pinal         07  46647.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.873601821172315, -112.03889480123648)

                                  best_width         link  \
0  (32.873601821172315, -112.03889480123648)  1040.140058

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1484105.7441689556 1215207.08...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:   6%|██▏                                     | 37/666 [00:00<00:06, 101.40it/s]

   intersection_id   zip county district population    state state_id  \
0             7572  8257  85138    Pinal         02  46647.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.01618677491856, -111.98642867897556)  (33.0151, -111.98681)

          link                                           geometry  \
0  9248.028054  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1484805.658357748 1220706.575020381...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7573  8258  85123    Pinal         07  17032.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.683759924157194, -111.70123443111483)

                                  best_width         link  \
0  (32.683759924157194, -111.70123443111483)  2287.863457

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1453757.8615252113 1183824.20...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7574  8259  85123    Pinal         06  17032.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (32.71842848595884, -111.67244262073021)  (32.70917, -111.6802)

          link                                           geometry  \
0  4633.510795  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1458020.8764866602 1197740.81750853...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7575  8260  85128    Pinal         05  17032.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.11806011263844, -111.60804012204508)

                                 best_width      link  \
0  (33.11806011263844, -111.60804012204508)  20.63144

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1443420.8063263262 1235476.10636948...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7576  8261  85128    Pinal         02  17032.0  Arizona

  center_lat                              lookup_lat              best_width  \
0         AZ  (32.968398468966, -111.51171388948407)  (32.96468, -111.51028)

           link                                           geometry  \
0  10662.979412  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1447668.2667486041 1228634.91761943...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7577  8262  85128    Pinal         06  17032.0  Arizona

  center_lat                              lookup_lat  \
0         AZ  (32.84034597415829, -111.460785136675)

                               best_width         link  \
0  (32.84034597415829, -111.460785136675)  2449.022334

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1424139.2838259253 1195442.42...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7578  8263  85140    Pinal         05  45352.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.238507915329215, -111.53119292499066)

                                  best_width        link  \
0  (33.238507915329215, -111.53119292499066)  7561.44521

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1436672.8051091079 1245878.58593718...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7579  8264  85140    Pinal         02  45352.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.2577919249168, -111.44647320940061)  (33.24805, -111.48921)

          link                                           geometry  \
0  9176.578406  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1419493.3987480998 1252978.71004625...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7580  8266  85147    Pinal         02  78246.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.094569932761836, -111.72091327387695)

              best_width         link  \
0  (33.09454, -111.7209)  7774.300145

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1462116.4585240954 1238818.57403793...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7581  8267  85631    Pinal         06  3521.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (32.58130922913826, -110.56251073759852)  (32.58133, -110.5627)

          link                                           geometry  \
0  14113.81183  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1342830.8280842728 1164841.50350398...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7582  8268  85118    Pinal         05  12504.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.33016625838918, -111.44931094362907)

                                 best_width         link  \
0  (33.33016625838918, -111.44931094362907)  2633.663262

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1424381.2899703314 1260358.95...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7583  8269  85118    Pinal         02  12504.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.37550583275189, -111.36193102276162)  (33.3737, -111.36545)

           link                                           geometry  \
0  17039.677509  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1421679.9849670115 1271256.81963551...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7584  8270  85193    Pinal         07  5303.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (32.74022178856293, -111.8460476644554)  (32.79822, -111.82809)

          link                                           geometry  \
0  7222.264913  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1482292.0467065407 1189195.19227586...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7585  8271  85193    Pinal         02  5303.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.948923719843094, -111.85660159618779)

                                  best_width         link  \
0  (32.948923719843094, -111.85660159618779)  6333.748888

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1473182.1668882554 1212863.30494272...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7586  8272  85193    Pinal         06  5303.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.82992371844091, -111.74926921810545)

                                 best_width         link  \
0  (32.82992371844091, -111.74926921810545)  5698.185337

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1463239.706144127 1215322.770512747...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7587  8273  85658    Pinal         06  15494.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.55824873902745, -111.14431873007412)

               best_width          link  \
0  (32.52455, -111.13603)  10729.555448

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1392963.3210230342 1158707.02055426...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7588  8274  85139    Pinal         07  18596.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.838549654865155, -112.11014936567666)

                                  best_width          link  \
0  (32.838549654865155, -112.11014936567666)  15570.932791

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1503295.7303155425 1197782.07...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7589  8275  85139    Pinal         02  18596.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.03417730991402, -112.12144682944034)

                                 best_width          link  \
0  (33.03417730991402, -112.12144682944034)  11445.489463

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1496853.325741393 1234456.628...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7590  8277  85248    Pinal         02  36274.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.177290233254844, -111.8370214128233)

                                 best_width         link  \
0  (33.177290233254844, -111.8370214128233)  2599.238662

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1466120.7131005956 1249094.82036018...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7591  8278  85618    Pinal         02  4927.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.84998294436335, -110.81005840484109)

               best_width          link  \
0  (32.77631, -110.69433)  14676.749693

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1340935.0536058128 1179928.27...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7592  8279  85618    Pinal         06  4927.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.70295978685657, -110.57912469534274)

                                 best_width          link  \
0  (32.70295978685657, -110.57912469534274)  13824.598223

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1340702.3480848246 1178713.52127871...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7593  8280  85623    Pinal         06  4927.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.653998556326115, -110.78448711912891)

               best_width          link  \
0  (32.65407, -110.78447)  14608.826561

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1364961.9030348998 1154587.31731803...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7594  8281  85739    Pinal         06  17216.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (32.63323094582318, -111.02962539431489)  (32.6137, -111.00758)

           link                                           geometry  \
0  12032.063094  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1379558.3720088077 1156877.08231127...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7595  8282  85119    Pinal         05  23792.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.3865137945601, -111.50912648635541)  (33.38682, -111.50824)

          link                                           geometry  \
0  6302.942762  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1427653.6888560867 1272235.57...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7596  8284  85119    Pinal         02  23792.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.40070728283627, -111.46826402580291)

                                 best_width         link  \
0  (33.40070728283627, -111.46826402580291)  1504.561573

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1422683.7970756285 1264839.95...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7597  8285  85120    Pinal         05  29062.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.384978515772715, -111.56124210267832)

               best_width         link  \
0  (33.38706, -111.56311)  3441.043249

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1434610.1977634411 1258915.16137416...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7598  8287  85172    Pinal         07  1849.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.84349296366471, -111.95891764746501)

                                 best_width        link  \
0  (32.84349296366471, -111.95891764746501)  5515.97616

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1484353.5820408904 1213730.32513583...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7599  8288  85172    Pinal         02  1849.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.93152436524157, -111.94814558544746)

               best_width         link  \
0  (32.89974, -111.95205)  9216.517706

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1484090.198289237 1215307.773794686...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7600  8289  85173    Pinal         02  2679.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.26827351699414, -111.13648179986167)

               best_width         link  \
0  (33.26827, -111.13651)  6067.395639

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1409824.8296137098 1246022.95019782...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  10%|███▉                                     | 64/666 [00:00<00:06, 92.93it/s]

   intersection_id   zip county district population    state state_id  \
0             7601  8291  85339    Pinal         02  50260.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.16103369062104, -112.11240394284542)

               best_width          link  \
0  (33.23985, -112.14322)  13736.121936

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1495199.1208444145 1244029.55985175...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7602  8292  85145    Pinal         07  3403.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.50949853122902, -111.46863381555785)

                                 best_width        link  \
0  (32.50949853122902, -111.46863381555785)  826.780346

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1440033.429811085 1165186.450...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7603  8293  85145    Pinal         06  3403.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.543692335836454, -111.39305233596832)

               best_width         link  \
0  (32.54322, -111.39415)  6227.272153

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1438382.5769232914 1168462.93236044...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7604  8294  85132    Pinal         05  38485.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.1471708947763, -111.47142410432703)

                                best_width        link  \
0  (33.1471708947763, -111.47142410432703)  365.032641

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1428153.2055962768 1235640.94691008...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7605  8295  85132    Pinal         02  38485.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (32.94234970868861, -111.2087153868968)  (32.92358, -111.19119)

           link                                           geometry  \
0  25056.191386  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1431677.704917751 1233571.138334808...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7606  8296  85132    Pinal         06  38485.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (32.7428511856684, -111.02070272520045)

                                best_width         link  \
0  (32.7428511856684, -111.02070272520045)  6854.874253

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1384066.7905698917 1186828.79...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7607  8298  85137    Pinal         02  2506.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.112655245161754, -110.98352361997767)

               best_width          link  \
0  (33.11275, -110.98353)  18314.393691

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1378067.6034226108 1240586.25948340...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population  state state_id  \
0             7608  8299  85141    Pinal         07  314.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.62615725650969, -111.48772914380662)

                                 best_width         link  \
0  (32.62615725650969, -111.48772914380662)  1648.407815

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1437967.6587634573 1177637.44...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population  state state_id  \
0             7609  8300  85141    Pinal         06  314.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.64778138394153, -111.42586680631021)

               best_width         link  \
0  (32.64707, -111.42792)  7584.537496

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1440053.2230678468 1187413.66315763...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7610  8301  85142    Pinal         05  78246.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.16768524362432, -111.6305762406211)  (33.19302, -111.66645)

          link                                           geometry  \
0  9100.258969  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1435794.210952726 1251409.812...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7611  8302  85142    Pinal         02  78246.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.174292331814996, -111.74352033074688)

                                  best_width         link  \
0  (33.174292331814996, -111.74352033074688)  7078.357747

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1447983.4787239367 1236199.14...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7612  8303  85143    Pinal         05  38548.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.152909742190744, -111.53195490559916)

               best_width         link  \
0  (33.15602, -111.51974)  4992.800763

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1436837.4374558125 1244846.12130096...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7613  8304  85143    Pinal         02  38548.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.17164039125751, -111.45846010340622)

                                 best_width         link  \
0  (33.17164039125751, -111.45846010340622)  2988.070704

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1427781.8256446847 1241184.23...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7614  8305  85192    Pinal         02  2239.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (32.87751031969297, -110.5903816308888)  (32.96134, -110.66501)

           link                                           geometry  \
0  18737.756094  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1367568.316569519 1208110.114271220...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7615  8307  85194    Pinal         02  7137.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.91176780137446, -111.61652452169142)

               best_width         link  \
0  (32.89675, -111.62439)  8378.528192

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1455569.57867649 1223767.2806593673...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7616  8308  85194    Pinal         06  7137.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.85532664090648, -111.64593116877364)

                                 best_width         link  \
0  (32.85532664090648, -111.64593116877364)  6334.638758

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1442500.8464967683 1203403.57...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7617  8309  85121    Pinal         02  46647.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.13751049473783, -111.91314327439916)

               best_width         link  \
0  (33.13751, -111.91316)  9181.572503

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1474495.6585359585 1250512.23816190...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7618  8310  85122    Pinal         02  54726.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.941962700190324, -111.75721822831262)

               best_width         link  \
0  (32.91672, -111.74798)  7102.880692

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1463885.623841437 1220189.884138127...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7619  8311  85122    Pinal         06  54726.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.87623866428801, -111.73313594909327)

                                 best_width         link  \
0  (32.87623866428801, -111.73313594909327)  4501.442168

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1452128.347735887 1211877.500514345...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7620  8312  85212    Pinal         05  43326.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.30914272978124, -111.57461194040442)

                                 best_width         link  \
0  (33.30914272978124, -111.57461194040442)  1836.851692

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1435653.7652690858 1252319.85136331...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7621  8313  85131    Pinal         07  17032.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.56762225979308, -111.60970949677521)

                                 best_width          link  \
0  (32.56762225979308, -111.60970949677521)  15560.976344

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1441222.7165082071 1165383.30939621...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7622  8314  85131    Pinal         02  17032.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.82821906535324, -111.51550507915138)

                                 best_width         link  \
0  (32.82821906535324, -111.51550507915138)  1497.061327

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1442262.1244715275 1203363.54910456...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  14%|█████▌                                  | 93/666 [00:00<00:04, 115.63it/s]

   intersection_id   zip county district population    state state_id  \
0             7623  8315  85131    Pinal         06  17032.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.73981485521235, -111.54445162460874)

               best_width          link  \
0  (32.65542, -111.57649)  10270.601448

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1453723.273113559 1184032.273...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7624  8316  85539    Pinal         02  2872.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.32211851148658, -111.00412027403954)

                                 best_width         link  \
0  (33.32211851148658, -111.00412027403954)  5542.186286

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1379324.7297692783 1251821.62953408...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7625  8318  85653    Pinal         06  19977.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.52338803913857, -111.31030381513234)

                                 best_width         link  \
0  (32.52338803913857, -111.31030381513234)  4921.056989

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1420969.3568440399 1162108.51206326...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population   state state_id  \
0             7626  8319  85634    Pinal         07  6288.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.545792324225964, -111.98784529832164)

                                  best_width         link  \
0  (32.545792324225964, -111.98784529832164)  7234.976087

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1478240.3580950003 1172151.51694671...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id   zip county district population    state state_id  \
0             7627  8320  85191    Pinal         02  17032.0  Arizona

  center_lat                             lookup_lat              best_width  \
0         AZ  (32.98497461914, -111.44685982876094)  (32.98498, -111.44686)

         link                                           geometry  \
0  882.656961  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1429034.473896983 1218440.87065043,...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population  state state_id  \
0             9672  10534  85928   Navajo         02  565.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (34.52268869340972, -110.55074778554541)  (34.52276, -110.5506)

           link                                           geometry  \
0  11540.002599  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1342251.0153772063 1350864.84520823...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9673  10535  85929   Navajo         02  7377.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (34.165148948801274, -109.95953733978321)

               best_width         link  \
0  (34.16512, -109.95948)  4108.976798

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1261759.690416241 1332003.030...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9674  10536  86039   Navajo         02  1590.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (35.98789346203889, -110.5671997370794)  (35.98813, -110.56688)

           link                                           geometry  \
0  10801.865458  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1318538.124447004 1502418.150571778...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9676  10539  86520   Navajo         02  3367.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (35.98395158143896, -110.0579834459122)

                                best_width         link  \
0  (35.98395158143896, -110.0579834459122)  9445.350054

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1245174.373684467 1538230.820838790...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population  state state_id  \
0             9677  10540  85911   Navajo         02  565.0  Arizona

  center_lat                               lookup_lat             best_width  \
0         AZ  (34.14840052662824, -110.4587478753897)  (34.14844, -110.4588)

           link                                           geometry  \
0  21588.678871  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1305323.6861342369 1313303.04234871...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9678  10541  86503   Navajo         02  3367.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (36.415372457054865, -110.07458243308056)

                                  best_width         link  \
0  (36.415372457054865, -110.07458243308056)  7862.670698

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1238860.9032867835 1580774.03640193...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population    state state_id  \
0             9679  10542  85912   Navajo         02  18855.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (34.4195053222251, -109.91619038684185)  (34.41962, -109.91624)

          link                                           geometry  \
0  7190.564648  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1257931.6389218336 1357570.49285223...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9680  10543  86054   Navajo         02  1590.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (36.68363060132818, -110.60302462308886)

               best_width          link  \
0  (36.67546, -110.61259)  19362.531067

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1304891.7658653003 1589632.22763342...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9681  10544  86054   Navajo         03  1590.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (37.001602451410456, -110.55968604355141)

                                  best_width        link  \
0  (37.001602451410456, -110.55968604355141)  464.768095

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1288163.2948451429 1650582.28951011...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9682  10545  85930   Navajo         02  2359.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.06531884458083, -109.88607236222235)

                                 best_width         link  \
0  (34.06531884458083, -109.88607236222235)  4755.003999

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1264852.3432008668 1317370.41...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9683  10546  86025   Navajo         02  5253.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.90456471886876, -110.08589666555187)

               best_width          link  \
0  (34.90484, -110.08557)  19481.009053

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1245861.7682436283 1436751.39654944...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9684  10547  86034   Navajo         02  1519.0  Arizona

  center_lat                                lookup_lat            best_width  \
0         AZ  (35.76898743829198, -110.15179343579345)  (35.77145, -110.138)

           link                                           geometry  \
0  23829.173457  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1248968.490042383 1512665.086959811...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9685  10548  86044   Navajo         02  3149.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (36.83493845610237, -110.69325714433867)

                                 best_width          link  \
0  (36.83493845610237, -110.69325714433867)  11673.677902

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1301766.5599156283 1609604.22...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9686  10549  86044   Navajo         03  3149.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (37.002783469060596, -110.69408468651639)

                                  best_width        link  \
0  (37.002783469060596, -110.69408468651639)  137.375207

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1294397.086191993 1651699.422611428...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population    state state_id  \
0             9687  10550  85901   Navajo         02  18855.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.29782519205784, -110.02031606688746)

               best_width          link  \
0  (34.29348, -109.99878)  19041.867672

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1259140.221663567 1349443.466972175...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population  state state_id  \
0             9688  10551  85923   Navajo         02  565.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.32312572131168, -110.34034600759534)

               best_width         link  \
0  (34.32313, -110.34036)  9939.994056

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1312389.702006714 1349057.496374965...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9689  10552  85926   Navajo         02  4429.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.77502950784444, -109.97883414633289)  (33.77507, -109.9788)

          link                                           geometry  \
0  3578.424539  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1282681.1071932837 1285474.94463295...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population  state state_id  \
0             9690  10553  85933   Navajo         02  565.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.36088805282783, -110.50955195034624)

               best_width         link  \
0  (34.36089, -110.50955)  9020.943015

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1330970.6560693048 1350005.41672805...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population    state state_id  \
0             9691  10554  85934   Navajo         02  18855.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.30248585434198, -110.24432367061759)

               best_width         link  \
0  (34.30251, -110.24432)  8358.987863

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1303741.510415906 1339958.590981999...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9692  10555  85937   Navajo         02  9058.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.56924144007747, -110.01291780022281)

               best_width          link  \
0  (34.56927, -110.01285)  19755.587042

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1254498.8988971224 1382453.65870614...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9693  10556  85935   Navajo         02  4429.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.14165618996617, -109.90456600682127)

               best_width        link  \
0  (34.14166, -109.90453)  7794.12943

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1261851.4271815561 1331396.87712991...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population    state state_id  \
0             9694  10557  86047   Navajo         02  14388.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (35.181927551796235, -110.53883735425465)

               best_width          link  \
0  (35.18181, -110.63785)  36305.300373

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1335937.8028170196 1391215.50905368...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9695  10558  85939   Navajo         02  9058.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.43728343384831, -110.08751847132581)

               best_width         link  \
0  (34.43729, -110.08754)  6591.580968

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1289090.7766415123 1361475.09970692...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population    state state_id  \
0             9696  10559  85941   Navajo         02  12903.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.910774421112826, -109.93890169777674)

                                  best_width          link  \
0  (33.910774421112826, -109.93890169777674)  12835.411982

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1265684.6584967305 1311752.28087711...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9697  10560  85942   Navajo         02  5253.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.77439985470499, -110.03549908009418)

               best_width         link  \
0  (34.77442, -110.03549)  1978.888841


Processing rows:  18%|███████▏                               | 122/666 [00:01<00:04, 124.89it/s]

   intersection_id    zip county district population   state state_id  \
0             9702  10565  86033   Navajo         02  1590.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (36.68002851985559, -110.27112049363626)

               best_width          link  \
0  (36.67692, -110.25536)  40556.655444

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1267846.5244991842 1646983.57272489...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9703  10566  86033   Navajo         03  1590.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (36.998198533103256, -110.06270882143772)

                                  best_width       link  \
0  (36.998198533103256, -110.06270882143772)  15.394148

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1243592.0722637237 1643368.31165818...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9704  10567  86042   Navajo         02  2207.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (35.86498363855506, -110.38446338729307)

               best_width         link  \
0  (35.86498, -110.38447)  7826.714571

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1288682.1162421359 1525271.49765201...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9705  10568  86043   Navajo         02  2609.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (35.81041924845255, -110.52906974199684)

               best_width          link  \
0  (35.81049, -110.52904)  13279.914243

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1307924.5472553975 1515412.68544109...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9706  10569  86505   Navajo         02  1855.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (35.52133614287587, -109.90785482342184)

                                 best_width          link  \
0  (35.52133614287587, -109.90785482342184)  13451.377127

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1248393.2540196846 1492836.80662833...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9707  10570  86510   Navajo         02  1590.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (36.23059171617968, -110.27161510028577)

               best_width          link  \
0  (36.23061, -110.27182)  31465.163895

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1307338.6149172431 1573994.32445254...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county district population   state state_id  \
0             9708  10572  85902   Navajo         02  7377.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (34.11507945125816, -110.16232339789029)

               best_width          link  \
0  (34.11509, -110.16233)  22318.893113

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1286175.3410894417 1310423.70536698...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16142  17525  85534  Greenlee         06  2681.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.729220256169086, -109.14486380216563)

               best_width          link  \
0  (32.72939, -109.14475)  22142.407801

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1208518.3481247034 1181880.93931236...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16143  17526  85533  Greenlee         02  3006.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.6440710922912, -109.45845717220993)

                                best_width        link  \
0  (33.6440710922912, -109.45845717220993)  501.276205

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1234155.864135615 1269318.964...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16144  17527  85533  Greenlee         06  3006.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.262018166252126, -109.33153457821305)

              best_width          link  \
0  (32.9781, -109.35704)  19380.217066

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1244625.7083825497 1223558.16366562...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16145  17528  85540  Greenlee         06  3795.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (32.97803595028167, -109.35700093593427)

                                 best_width         link  \
0  (32.97803595028167, -109.35700093593427)  9172.465367

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1237289.9274383655 1174297.26589725...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16146  17529  85922  Greenlee         02  3006.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.757475430897124, -109.35524616713246)

                                  best_width        link  \
0  (33.757475430897124, -109.35524616713246)  263.052609

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1196645.9536632467 1272429.87...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16147  17530  85922  Greenlee         06  3006.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.49512191993024, -109.18861212244533)

               best_width          link  \
0  (33.49535, -109.18864)  26664.232823

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1224584.7514552649 1270864.61273310...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16148  17531  85922  Greenlee         02  3006.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.41068500167028, -109.04714595927473)

                                 best_width       link  \
0  (33.41068500167028, -109.04714595927473)  17.835065

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1199097.0173053264 1249672.17...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16149  17532  85008  Maricopa         04  59734.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.44738743938385, -111.96300241535008)

                                 best_width     link  \
0  (33.44738743938385, -111.96300241535008)  380.383

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1466059.5073696652 1276559.48...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16150  17533  85008  Maricopa         01  59734.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.46423416628013, -111.96524886832579)

                                 best_width         link  \
0  (33.46423416628013, -111.96524886832579)  2601.788523

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1470384.9468636224 1281046.58274910...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16151  17534  85008  Maricopa         03  59734.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.463427714558556, -112.00714646209383)

               best_width         link  \
0  (33.46355, -111.98746)  3044.411658

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1472826.6369277663 1280919.55540534...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16152  17535  85032  Maricopa         01  69352.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.62624104025461, -112.00366898606114)

               best_width        link  \
0  (33.62624, -112.00368)  4703.84399

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1469907.2641572782 1300329.71409958...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16153  17536  85054  Maricopa         01  8131.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.67512169278283, -111.94760166288059)

               best_width         link  \
0  (33.67515, -111.94763)  3943.011029

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1464175.4517524918 1301935.21341732...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16154  17537  85085  Maricopa         08  26505.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.75651659954126, -112.07421768290045)

               best_width         link  \
0  (33.75637, -112.07426)  8597.992897

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1476185.481532089 1318039.100039930...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16155  17538  85085  Maricopa         01  26505.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.69904045587025, -112.09250079206072)

                                 best_width        link  \
0  (33.69904045587025, -112.09250079206072)  163.618967

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1473372.7018113704 1306262.40...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16156  17540  85204  Maricopa         04  67614.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.396656629430105, -111.78783084686366)

               best_width         link  \
0  (33.39666, -111.78786)  3770.023142

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1455819.4476960618 1267217.09942838...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16157  17541  85257  Maricopa         04  30647.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.439322020332355, -111.90088036885604)

                                  best_width        link  \
0  (33.439322020332355, -111.90088036885604)  617.390628

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1460703.7446874632 1274890.71240671...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16158  17542  85257  Maricopa         01  30647.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.46493114363217, -111.91566874872456)

               best_width         link  \
0  (33.46354, -111.91486)  2802.594221

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1466431.107757925 1279906.859742083...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16159  17543  85266  Maricopa         01  12145.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.76036092016517, -111.92501475874754)

               best_width         link  \
0  (33.76034, -111.92503)  3969.633944

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1463050.0494249845 1309296.29648375...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16160  17545  85355  Maricopa         09  12713.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.57517966677957, -112.45372393785341)

               best_width         link  \
0  (33.57519, -112.45374)  4366.757315

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1514862.3718291903 1299015.07469112...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16161  17546  85378  Maricopa         08  20366.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.647065312631376, -112.31553956601586)

               best_width         link  \
0  (33.64162, -112.32012)  1473.289644

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1496675.4440454568 1303499.43...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16162  17547  85378  Maricopa         09  20366.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.633523040249784, -112.32689834770947)

                                  best_width         link  \
0  (33.633523040249784, -112.32689834770947)  1172.654092

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1497590.2772799297 1303654.70639055...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16163  17548  85043  Maricopa         03  38938.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.43172937253604, -112.19659692340231)  (33.4323, -112.19744)

          link                                           geometry  \
0  5886.585385  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1493317.3686184895 1276758.40959069...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16164  17549  85043  Maricopa         07  38938.0  Arizona

  center_lat                                 lookup_lat  \

Processing rows:  23%|████████▊                              | 150/666 [00:01<00:03, 130.79it/s]

   intersection_id    zip county  district population    state state_id  \
0            16166  17551  85233  Maricopa         04  37651.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.36841530811553, -111.84051204680476)

                                 best_width        link  \
0  (33.36841530811553, -111.84051204680476)  319.676269

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1454005.0125715733 1266781.66...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16167  17552  85297  Maricopa         05  34349.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.27843239089468, -111.73635631001522)

               best_width         link  \
0  (33.27843, -111.73638)  3179.554779

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1454420.4135201764 1255925.31814078...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16168  17553  85323  Maricopa         09  44512.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.43655229786586, -112.3508114605889)

                                best_width        link  \
0  (33.43655229786586, -112.3508114605889)  536.527129

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1501450.3615301643 1283325.44...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16169  17554  85323  Maricopa         07  44512.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.41817419506599, -112.32514182856036)

               best_width         link  \
0  (33.41888, -112.32615)  3643.792682

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1504108.9793164937 1276816.01068050...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16170  17556  85373  Maricopa         08  20366.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.67235205042381, -112.29958533400216)

               best_width        link  \
0  (33.67257, -112.29983)  3087.99129

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1496401.6074384116 1308543.95438954...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16171  17557  85373  Maricopa         09  20366.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.69694133202433, -112.3303065865456)

                                best_width        link  \
0  (33.69694133202433, -112.3303065865456)  330.225661

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1496027.2112348494 1309817.00222718...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16172  17558  85390  Maricopa         09  9317.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.88508899158038, -112.91020952981582)

               best_width          link  \
0  (33.92391, -112.86739)  24720.085353

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1553863.8709671402 1354641.40410442...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16173  17561  85213  Maricopa         04  37247.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.44110336940449, -111.76931880607272)

               best_width         link  \
0  (33.44764, -111.76962)  3140.368035

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1451132.9000764631 1275585.82902276...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16174  17562  85213  Maricopa         01  37247.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.47476170303989, -111.77096733439758)

                                 best_width         link  \
0  (33.47476170303989, -111.77096733439758)  1417.689292

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1451115.5918332639 1275618.14320788...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16175  17563  85283  Maricopa         04  46375.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.364433176035526, -111.9277511257386)

               best_width         link  \
0  (33.36461, -111.93196)  3203.874634

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1468276.4777518082 1269111.86022713...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16176  17564  85283  Maricopa         03  46375.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.36571341689944, -111.96551219466875)

                                 best_width         link  \
0  (33.36571341689944, -111.96551219466875)  1051.309092

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1469852.189219928 1269370.788798628...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16177  17565  85007  Maricopa         03  14169.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.44679892952265, -112.09073306493286)

               best_width         link  \
0  (33.44682, -112.09073)  1610.583252

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1479455.4523614289 1279921.96090418...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16178  17566  85298  Maricopa         05  40894.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.2398179753318, -111.72819814811285)  (33.23983, -111.72819)

          link                                           geometry  \
0  4428.031036  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1451402.6561941695 1246618.21403581...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16179  17567  85307  Maricopa         08  11665.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.54958072872485, -112.2840421066321)

                                best_width        link  \
0  (33.54958072872485, -112.2840421066321)  452.452323

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1496471.88874502 1293497.8514665598...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16180  17568  85307  Maricopa         09  11665.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.53346813924404, -112.30945148145507)

               best_width        link  \
0  (33.53396, -112.30867)  3171.24061

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1501109.9892720454 1294356.85330821...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16181  17569  85003  Maricopa         03  8105.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.45052028988798, -112.07834348158848)

               best_width        link  \
0  (33.45059, -112.07833)  792.328363

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477175.255031746 1282083.886601559...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16182  17570  85012  Maricopa         01  7861.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.526859687984825, -112.06948137321919)

                                  best_width        link  \
0  (33.526859687984825, -112.06948137321919)  802.997213

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1475910.698394242 1286236.098457125...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16183  17571  85012  Maricopa         03  7861.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.496573123076914, -112.0706634758122)

               best_width        link  \
0  (33.50719, -112.07024)  882.645756

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477018.8903630925 1282581.52110730...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16184  17572  85013  Maricopa         01  20163.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.52967995551387, -112.0815679644936)

                                best_width         link  \
0  (33.52967995551387, -112.0815679644936)  1368.173788

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477313.279046543 1287565.977401533...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16185  17573  85013  Maricopa         03  20163.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.50195555113877, -112.08346495708037)

               best_width         link  \
0  (33.51001, -112.08294)  1238.628311

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1478151.1798243911 1282780.34661302...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16186  17574  85018  Maricopa         01  37558.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.51959152744454, -111.99302862184588)  (33.5194, -111.99309)

          link                                           geometry  \
0  4041.943825  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1470697.024320597 1284846.519...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16187  17575  85018  Maricopa         03  37558.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.48210278121133, -112.0112835076145)

                                best_width        link  \
0  (33.48210278121133, -112.0112835076145)  292.383706

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1470485.5350775092 1281064.02603149...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16188  17576  85250  Maricopa         01  15937.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.52986936106556, -111.88990224873305)

               best_width         link  \
0  (33.52986, -111.88991)  2985.486965

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1462594.5450701641 1283259.26...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16189  17577  85331  Maricopa         08  30647.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.80295498357639, -112.01599995835181)

                                 best_width         link  \
0  (33.80295498357639, -112.01599995835181)  1774.605872

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1466650.6996468725 1308286.65709482...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16190  17578  85331  Maricopa         01  30647.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.89292524604864, -111.9374527986251)  (33.88685, -111.94276)

           link                                           geometry  \
0  11439.400173  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1462097.1647752973 1327298.03983106...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16191  17579  85338  Maricopa         09  57464.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.37251728021994, -112.40954056950454)

               best_width         link  \
0  (33.37252, -112.40826)  9403.267348

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1515888.6848620987 1274637.47288809...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16192  17580  85338  Maricopa         07  57464.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.372434376594676, -112.34575338263043)

                                  best_width         link  \
0  (33.372434376594676, -112.34575338263043)  1164.591469

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1504212.1440083054 1276163.76...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  27%|██████████▍                            | 178/666 [00:01<00:03, 129.92it/s]

   intersection_id    zip county  district population   state state_id  \
0            16193  17581  85004  Maricopa         03  9071.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.45160957454662, -112.0698795605901)  (33.45159, -112.06988)

         link                                           geometry  \
0  810.842466  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477015.437003151 1280931.772956479...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16194  17582  85028  Maricopa         01  18136.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.58160591211442, -112.00813557536966)  (33.5816, -112.00811)

          link                                           geometry  \
0  3227.441378  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1471643.134026032 1292370.299921754...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16195  17583  85034  Maricopa         04  5001.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.44191806291307, -111.9708613652534)

                                best_width        link  \
0  (33.44191806291307, -111.9708613652534)  1101.78175

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1468512.0089757342 1277275.22755491...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16196  17584  85034  Maricopa         01  5001.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.451017197841246, -111.979417865032)

                                best_width       link  \
0  (33.451017197841246, -111.979417865032)  28.210335

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1468742.9761937293 1277445.71883311...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16197  17585  85034  Maricopa         03  5001.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.434147222669765, -112.02327373829984)

               best_width         link  \
0  (33.43465, -112.01989)  3476.125038

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477137.9801606755 1276241.56455347...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16198  17586  85086  Maricopa         08  43083.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.826394585052235, -112.12879510204996)

               best_width         link  \
0  (33.82639, -112.12876)  7931.170728

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1485682.2191136992 1320500.33420619...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16199  17587  85139  Maricopa         07  18596.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.958332274146144, -112.32102679270494)

               best_width          link  \
0  (32.92096, -112.21117)  20024.251468

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1496923.661698979 1234468.851250893...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16200  17588  85139  Maricopa         02  18596.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.07987416367595, -112.20241206161818)

                                 best_width       link  \
0  (33.07987416367595, -112.20241206161818)  17.946519

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1495011.255374485 1245120.235385244...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16201  17589  85248  Maricopa         05  36274.0  Arizona

  center_lat                               lookup_lat             best_width  \
0         AZ  (33.23259375312033, -111.8662586785094)  (33.2145, -111.86667)

          link                                           geometry  \
0  4721.678954  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1460568.3499578913 1248077.84972214...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16202  17590  85248  Maricopa         02  36274.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.24197640539984, -111.91470170463892)

                                 best_width         link  \
0  (33.24197640539984, -111.91470170463892)  3708.903613

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1463318.7224613097 1248492.93...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16203  17591  85302  Maricopa         08  40946.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.567778088463896, -112.17819100742182)

               best_width         link  \
0  (33.56777, -112.17819)  3106.395912

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1487456.5200408697 1292972.88406001...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population  state state_id  \
0            16204  17592  85322  Maricopa         09  443.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.24991215357594, -112.83399712242391)

                                 best_width          link  \
0  (33.24991215357594, -112.83399712242391)  12680.541179

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1568702.379333093 1267032.20784366,...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population  state state_id  \
0            16205  17593  85322  Maricopa         07  443.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.10675853952982, -112.86920623549717)  (33.1766, -112.85207)

           link                                           geometry  \
0  16777.247833  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1540358.9529535882 1251794.36668955...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16206  17594  85361  Maricopa         09  6970.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.76618485828059, -112.63087281327174)

               best_width         link  \
0  (33.76617, -112.63093)  7935.287501

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1536220.475907261 1320758.204419708...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16207  17595  85387  Maricopa         08  14518.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.71351425913536, -112.38633734233109)

                                 best_width        link  \
0  (33.71351425913536, -112.38633734233109)  376.144347

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1497589.4346737552 1315836.38...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16208  17596  85387  Maricopa         09  14518.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.710255657740056, -112.448865732227)  (33.71025, -112.44869)

          link                                           geometry  \
0  7183.535269  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1517799.4857777427 1310294.48730802...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16209  17597  85016  Maricopa         01  36320.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.51647862172658, -112.0290876811461)  (33.50953, -112.03041)

          link                                           geometry  \
0  2991.314264  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1473539.229740301 1286992.659948775...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16210  17598  85016  Maricopa         03  36320.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.48760994541907, -112.03461733357159)

                                 best_width        link  \
0  (33.48760994541907, -112.03461733357159)  1648.01839

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1471012.6618657487 1281575.43...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16211  17599  85022  Maricopa         01  50320.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.626873767125566, -112.05114115813927)

               best_width         link  \
0  (33.62685, -112.05113)  3985.255421

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1473587.5800989068 1300077.40...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16212  17600  85120  Maricopa         05  29062.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.417887698455395, -111.59178098569276)

                                  best_width        link  \
0  (33.417887698455395, -111.59178098569276)  938.692587

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1432030.392371518 1272748.424...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16213  17602  85215  Maricopa         05  16013.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.47520575955081, -111.59478145639594)

                                 best_width         link  \
0  (33.47520575955081, -111.59478145639594)  1326.489467

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1427585.898450977 1272223.946...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16214  17603  85215  Maricopa         04  16013.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.46924326502897, -111.71337387998729)

                                 best_width         link  \
0  (33.46924326502897, -111.71337387998729)  4091.272711

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1441051.1188494114 1276630.06800319...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16215  17604  85215  Maricopa         01  16013.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.517464611014006, -111.56118490207878)

               best_width         link  \
0  (33.51101, -111.58027)  9679.691218

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1423044.4689916326 1271480.53...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16216  17605  85282  Maricopa         04  52066.0  Arizona

  center_lat                               lookup_lat             best_width  \
0         AZ  (33.39424030284506, -111.9257202189024)  (33.3943, -111.93242)

          link                                           geometry  \
0  3158.576096  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1468572.8458337123 1273004.87472162...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16217  17606  85282  Maricopa         03  52066.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.394579622953934, -111.97249433948657)

                                  best_width         link  \
0  (33.394579622953934, -111.97249433948657)  1200.122051

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1469560.0202709595 1271110.86324197...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16218  17607  85308  Maricopa         08  63827.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.66028507810154, -112.18490670601072)

               best_width        link  \
0  (33.69532, -112.17162)  4752.15872

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1488740.5371816526 1302120.43953471...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population  state state_id  \
0            16219  17608  85333  Maricopa         09  501.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.142811889062855, -113.21671955587799)

                                  best_width          link  \
0  (33.142811889062855, -113.21671955587799)  14051.112327

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1600389.1097811866 1252256.02...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population  state state_id  \
0            16220  17609  85333  Maricopa         07  501.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (32.951795909518296, -113.19287798294688)

               best_width          link  \
0  (32.97896, -113.30714)  19458.147019

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1570349.1478908623 1265791.47...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16221  17610  85351  Maricopa         08  28095.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.606341389258944, -112.28206798929614)

               best_width         link  \
0  (33.60638, -112.28213)  3737.347241

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1495000.2770333102 1302296.29943336...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  31%|████████████                           | 207/666 [00:01<00:03, 134.10it/s]

   intersection_id    zip county  district population    state state_id  \
0            16222  17611  85351  Maricopa         09  28095.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.62807296865791, -112.30806586677814)

                                 best_width        link  \
0  (33.62807296865791, -112.30806586677814)  117.852232

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1495151.9098947481 1302324.50611748...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16223  17612  85009  Maricopa         03  51713.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.44455887022423, -112.12660508106387)

               best_width         link  \
0  (33.44457, -112.12661)  4715.259077

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1486452.7987734547 1275882.80406546...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16224  17613  85021  Maricopa         08  39611.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.56083665503496, -112.10856033223574)

                                 best_width        link  \
0  (33.56083665503496, -112.10856033223574)  1274.19999

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1478854.7617728575 1292758.67367737...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16225  17614  85021  Maricopa         01  39611.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.56026692583286, -112.08825799550544)

               best_width         link  \
0  (33.56046, -112.09442)  2459.055164

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477487.5842776857 1293513.82549028...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16226  17615  85024  Maricopa         08  24947.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.71116745264039, -112.04342332637063)

                                 best_width         link  \
0  (33.71116745264039, -112.04342332637063)  2295.721998

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1473332.9179080676 1306431.84501458...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16227  17616  85024  Maricopa         01  24947.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.678712593414964, -112.04795480733269)

               best_width         link  \
0  (33.69042, -112.04632)  3146.495866

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1473342.4388505798 1306392.47...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16228  17617  85027  Maricopa         08  38136.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.67627872089573, -112.12323816594932)

                                 best_width         link  \
0  (33.67627872089573, -112.12323816594932)  2101.720644

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1475045.0599676485 1306737.26...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16229  17618  85027  Maricopa         01  38136.0  Arizona

  center_lat                               lookup_lat             best_width  \
0         AZ  (33.67751576966415, -112.0908315588479)  (33.6771, -112.10206)

          link                                           geometry  \
0  3801.748669  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1475329.9211496466 1306725.03029088...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16230  17619  85035  Maricopa         03  54524.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.47166860028382, -112.19539225817671)

               best_width         link  \
0  (33.47167, -112.19538)  1929.007864

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1491808.1277534666 1283175.83105717...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16231  17620  85035  Maricopa         07  54524.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.46541117345691, -112.2378836162131)

                                best_width       link  \
0  (33.46541117345691, -112.2378836162131)  15.270099

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1491846.0821435496 1283008.53386021...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16232  17621  85048  Maricopa         04  34039.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.30370671654594, -112.03202627170927)

               best_width         link  \
0  (33.30362, -112.03192)  3179.991158

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1479263.5114157677 1264344.78657487...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16233  17622  85048  Maricopa         02  34039.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.290760388901354, -112.01751220706652)

                                  best_width      link  \
0  (33.290760388901354, -112.01751220706652)  11.42122

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1470860.9536005629 1259650.16455124...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16234  17624  85210  Maricopa         04  40292.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.38955105565126, -111.84338088861324)

               best_width         link  \
0  (33.38955, -111.84337)  3108.930584

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1459346.236940517 1267773.913881361...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16235  17625  85339  Maricopa         04  50260.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.309088942702225, -112.11627186201991)

                                  best_width         link  \
0  (33.309088942702225, -112.11627186201991)  1131.283856

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1482233.832407795 1263889.456907964...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16236  17626  85339  Maricopa         03  50260.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.35835893908414, -112.1608198034121)

                                best_width         link  \
0  (33.35835893908414, -112.1608198034121)  5769.129694

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1493205.9463386012 1274656.84...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16237  17627  85339  Maricopa         07  50260.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.317385709428386, -112.27924602268318)

                                  best_width        link  \
0  (33.317385709428386, -112.27924602268318)  268.135331

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1493074.4654547127 1258464.37...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16238  17628  85339  Maricopa         02  50260.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.28708695620083, -112.16928465676145)

                                 best_width         link  \
0  (33.28708695620083, -112.16928465676145)  9533.519537

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1474664.8927793787 1250540.88013122...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16239  17629  85353  Maricopa         03  42058.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.414560927723315, -112.25407122218763)

                                  best_width        link  \
0  (33.414560927723315, -112.25407122218763)  2966.73572

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1490591.5000981966 1281246.29352415...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16240  17630  85353  Maricopa         07  42058.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.41950903149261, -112.28430441898008)

               best_width         link  \
0  (33.41721, -112.27283)  3931.446978

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1500475.1022238315 1279425.35215121...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16241  17631  85353  Maricopa         02  42058.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.38400080878805, -112.25638007433103)

                                 best_width        link  \
0  (33.38400080878805, -112.25638007433103)  381.071717

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1493227.9173463203 1274528.96...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16242  17632  85019  Maricopa         08  29084.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.53842772833026, -112.13785156519674)

                                 best_width      link  \
0  (33.53842772833026, -112.13785156519674)  18.37773

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1481319.9610349762 1289489.34595520...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16243  17633  85019  Maricopa         03  29084.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.50946114861144, -112.14308329710903)

               best_width         link  \
0  (33.50952, -112.14307)  1570.693446

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1483123.9021137124 1286724.56175404...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16244  17634  85006  Maricopa         03  24777.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.465111488089974, -112.04777842509785)

               best_width         link  \
0  (33.46511, -112.04778)  2795.644533

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1476342.235013529 1279593.706129443...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16245  17635  85020  Maricopa         01  33582.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.567629774701956, -112.0548251312979)

               best_width         link  \
0  (33.56766, -112.05485)  3160.983211

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1475443.764968327 1291784.114971924...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16246  17636  85014  Maricopa         01  26120.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.523203614394546, -112.05621873135817)

               best_width         link  \
0  (33.50903, -112.05665)  1576.997809

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1475242.5766446718 1285544.30...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16247  17637  85014  Maricopa         03  26120.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.494058621017295, -112.05709699416546)

                                  best_width         link  \
0  (33.494058621017295, -112.05709699416546)  1587.788533

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1475911.4230728182 1282676.10535111...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16248  17638  85015  Maricopa         08  41848.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.53548939678741, -112.1057992467227)

                                best_width        link  \
0  (33.53548939678741, -112.1057992467227)  686.042798

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1479103.2886235924 1288628.88945631...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16249  17639  85015  Maricopa         01  41848.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.533231816872394, -112.09466218689161)

                                  best_width        link  \
0  (33.533231816872394, -112.09466218689161)  679.053157

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477917.009619503 1288660.339395821...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  35%|█████████████▊                         | 235/666 [00:01<00:03, 133.85it/s]

   intersection_id    zip county  district population    state state_id  \
0            16250  17640  85015  Maricopa         03  41848.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.505634283961506, -112.1020272516206)

               best_width         link  \
0  (33.50908, -112.10184)  1994.713114

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1480046.0665973416 1283526.34981233...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16251  17641  85017  Maricopa         08  41195.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.53686017786717, -112.12132619549445)

                                 best_width        link  \
0  (33.53686017786717, -112.12132619549445)  345.124429

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1481321.4521500543 1289480.64937985...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16252  17642  85017  Maricopa         03  41195.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.50758466987568, -112.12394960279725)

               best_width         link  \
0  (33.50898, -112.12381)  2032.003279

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1482465.2744288999 1283332.82417072...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16253  17643  85031  Maricopa         03  33410.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.49489683496832, -112.16833693284634)

               best_width         link  \
0  (33.49491, -112.16835)  2678.450575

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1486569.1786724527 1285625.27261289...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16254  17644  85045  Maricopa         04  6645.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.299904750336374, -112.10551380865604)

              best_width         link  \
0  (33.29976, -112.1062)  1610.390422

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1486235.045093859 1263841.225480870...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16255  17645  85045  Maricopa         02  6645.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.29403269189579, -112.13311753651337)

                                 best_width        link  \
0  (33.29403269189579, -112.13311753651337)  206.328306

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1485601.7639211447 1262101.62...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16256  17646  85051  Maricopa         08  43623.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.55930441687315, -112.13311170086835)

               best_width         link  \
0  (33.55914, -112.13324)  3376.581167

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1481984.9158948592 1293382.18586007...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16257  17647  85051  Maricopa         03  43623.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.5374872019233, -112.14794129887603)

                                best_width        link  \
0  (33.5374872019233, -112.14794129887603)  253.427278

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1481423.6347460593 1289498.17023294...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16258  17648  85053  Maricopa         08  28939.0  Arizona

  center_lat                                lookup_lat             best_width  \
0         AZ  (33.62959506348164, -112.13184613484599)  (33.6296, -112.13184)

          link                                           geometry  \
0  2981.786832  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1480248.0649280834 1300739.99615554...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16259  17649  85326  Maricopa         09  71621.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.28703803738703, -112.59440678864874)

               best_width          link  \
0  (33.23735, -112.58538)  20733.821359

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1544162.9486918182 1271184.44396193...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16260  17650  85326  Maricopa         07  71621.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.08491452480346, -112.55785367833671)

                                 best_width          link  \
0  (33.08491452480346, -112.55785367833671)  11862.805405

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1507983.942120359 1254459.437716825...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16261  17651  85268  Maricopa         01  23810.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.60717486885793, -111.73999149584284)

               best_width         link  \
0  (33.60717, -111.73999)  5569.106669

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1447796.0217403222 1294117.18733337...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16262  17652  85234  Maricopa         05  50328.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.36452594970662, -111.73950511858186)

               best_width         link  \
0  (33.36479, -111.73924)  3194.178697

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1452881.9855040463 1265356.38620519...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16263  17653  85234  Maricopa         04  50328.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.383612331080776, -111.72339272369565)

                                  best_width        link  \
0  (33.383612331080776, -111.72339272369565)  335.197263

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1449024.2545547825 1265972.10...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16264  17654  85254  Maricopa         01  44752.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.61471625151276, -111.95172401814075)

               best_width         link  \
0  (33.61474, -111.95176)  4594.794232

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1465717.5164665524 1293560.93835416...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16265  17655  85256  Maricopa         04  5014.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.43829456056838, -111.88303007647721)

                                 best_width        link  \
0  (33.43829456056838, -111.88303007647721)  382.641824

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1459067.3482143807 1274350.00108911...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16266  17656  85256  Maricopa         01  5014.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.50085589495066, -111.83498190578729)

               best_width         link  \
0  (33.50053, -111.83524)  6008.536234

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1460305.5979900593 1277878.02749154...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16267  17657  85296  Maricopa         05  49252.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.335537613126384, -111.74006417177709)

               best_width         link  \
0  (33.33554, -111.74006)  3147.893476

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1454193.2652729184 1261186.92...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16268  17658  85023  Maricopa         08  33985.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.62959207249623, -112.11216703096166)

                                 best_width        link  \
0  (33.62959207249623, -112.11216703096166)  851.356216

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477942.2154421648 1297752.53332785...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16269  17659  85023  Maricopa         01  33985.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.631949512697005, -112.09095174456453)

               best_width         link  \
0  (33.63156, -112.09452)  2952.574305

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1476690.7865154236 1301721.74018193...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16270  17660  85251  Maricopa         01  40017.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.4940496125647, -111.92028455300789)  (33.49406, -111.92025)

          link                                           geometry  \
0  3225.273081  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1466074.895138679 1280241.909252352...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16271  17661  85253  Maricopa         01  17212.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.54477669949337, -111.95874442093795)

               best_width         link  \
0  (33.54479, -111.95873)  5292.984687

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1470227.157330317 1286272.793903321...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16272  17662  85301  Maricopa         08  67736.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.547059639875606, -112.1790365981099)

                                 best_width         link  \
0  (33.547059639875606, -112.1790365981099)  1678.320812

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1488312.8767129069 1293909.38809916...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16273  17663  85301  Maricopa         09  67736.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.530347127834055, -112.20492605778607)

                                  best_width        link  \
0  (33.530347127834055, -112.20492605778607)  230.164039

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1487452.8898227136 1289540.82...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16274  17664  85301  Maricopa         03  67736.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.523933560162384, -112.17734202239194)

               best_width         link  \
0  (33.53219, -112.17817)  3229.691677

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1482602.3158223494 1289703.87704142...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16275  17665  85029  Maricopa         08  47886.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.59574838634042, -112.12815443230761)

               best_width         link  \
0  (33.59546, -112.11002)  2861.855012

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1481773.3009412298 1294504.08667328...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16276  17666  85029  Maricopa         01  47886.0  Arizona

  center_lat                              lookup_lat  \
0         AZ  (33.5950723074216, -112.0866128765334)

                               best_width         link  \
0  (33.5950723074216, -112.0866128765334)  2698.453372

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477105.3451142898 1296982.24816879...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16277  17667  85142  Maricopa         05  78246.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.2397425690764, -111.64069025898648)

                                best_width         link  \
0  (33.2397425690764, -111.64069025898648)  7833.850077

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1435667.2796193836 1252208.12904292...

                                            response
0  {"success": true, "data": {"districts": [{"id"...

Processing rows:  39%|███████████████▍                       | 263/666 [00:02<00:03, 131.04it/s]

   intersection_id    zip county  district population    state state_id  \
0            16278  17668  85255  Maricopa         01  41888.0  Arizona

  center_lat                                lookup_lat            best_width  \
0         AZ  (33.68241227937502, -111.81767755049383)  (33.6824, -111.8177)

          link                                           geometry  \
0  9236.900473  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1462047.4473575128 1305228.22052033...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16279  17669  85304  Maricopa         08  28587.0  Arizona

  center_lat                              lookup_lat              best_width  \
0         AZ  (33.5956525493222, -112.1781378137049)  (33.59566, -112.17815)

         link                                           geometry  \
0  2662.93181  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1486366.0282929267 1295798.10168886...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16280  17670  85033  Maricopa         09  60114.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.50742512040271, -112.22604201350774)

                                 best_width        link  \
0  (33.50742512040271, -112.22604201350774)  449.257806

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1491081.9496339867 1287293.21802922...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16281  17671  85033  Maricopa         03  60114.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.493720514427444, -112.21114786850426)

               best_width         link  \
0  (33.49443, -112.21193)  2983.871548

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1491563.6102294864 1286241.29278638...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16282  17672  85037  Maricopa         09  52061.0  Arizona

  center_lat                               lookup_lat  \
0         AZ  (33.5030658342983, -112.27952481764214)

                                best_width         link  \
0  (33.5030658342983, -112.27952481764214)  1382.128447

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1498104.0711891206 1287280.10741466...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16283  17673  85037  Maricopa         03  52061.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.48987811996497, -112.25528394678761)

               best_width         link  \
0  (33.49038, -112.26487)  1844.086957

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1491087.2968020083 1287263.31363269...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16284  17674  85037  Maricopa         07  52061.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.47439347964241, -112.26121691830134)

                                 best_width         link  \
0  (33.47439347964241, -112.26121691830134)  1774.471446

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1494448.7394193537 1286683.82...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16285  17675  85264  Maricopa         01  1374.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.69742196644123, -111.5029857168327)  (33.69996, -111.50123)

           link                                           geometry  \
0  24631.974388  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1411722.1327351464 1322318.10780213...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16286  17676  85264  Maricopa         02  1374.0  Arizona

  center_lat                             lookup_lat  \
0         AZ  (33.85438877579, -111.39418336246007)

                              best_width         link  \
0  (33.85438877579, -111.39418336246007)  2613.136182

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1399895.2921361427 1285295.62...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16287  17677  85263  Maricopa         01  3083.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.89916320224275, -111.62602869580692)

               best_width          link  \
0  (33.90026, -111.62412)  15745.537213

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1434464.0967293475 1333861.12916127...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population   state state_id  \
0            16288  17678  85263  Maricopa         02  3083.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.996313301993595, -111.46099019173184)

                                  best_width         link  \
0  (33.996313301993595, -111.46099019173184)  1306.617813

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1414125.7243327675 1330582.56...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16289  17679  85258  Maricopa         01  25343.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.563364568832824, -111.89269602878827)

               best_width         link  \
0  (33.56337, -111.89268)  4471.190849

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1461411.5289978168 1290254.51202503...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16290  17680  85259  Maricopa         01  22402.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.60104107373107, -111.8094971435862)  (33.60105, -111.80952)

         link                                           geometry  \
0  5877.41895  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1454325.2780742084 1293176.08882913...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16291  17681  85303  Maricopa         08  34617.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.54960731085018, -112.22036311379085)

                                 best_width         link  \
0  (33.54960731085018, -112.22036311379085)  2151.001384

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1490077.458582964 1293093.647740678...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16292  17682  85303  Maricopa         09  34617.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.524642927664935, -112.22113065305568)

               best_width         link  \
0  (33.53398, -112.22084)  2972.374345

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1487302.237075989 1290398.993288634...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16293  17684  85040  Maricopa         03  33802.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.40584892418589, -112.02657108914096)

               best_width         link  \
0  (33.40585, -112.02658)  2869.629401

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1478513.587492771 1275469.250746281...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16294  17685  85041  Maricopa         03  62369.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.386438514724226, -112.1093204685429)

               best_width         link  \
0  (33.38643, -112.10928)  3958.521006

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1485909.2433292011 1275402.74215510...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16295  17686  85050  Maricopa         01  31248.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.68736945672843, -111.99852026272437)

               best_width         link  \
0  (33.68739, -111.99854)  4683.393338

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1468866.1596622257 1304186.41058135...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16296  17687  85260  Maricopa         01  38320.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.60944127737248, -111.89108845101669)

               best_width         link  \
0  (33.60943, -111.89113)  5285.688535

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1460844.0661676954 1293053.04256493...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16297  17688  85262  Maricopa         01  12701.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.85824412245118, -111.80169890248091)

               best_width          link  \
0  (33.85834, -111.80169)  11072.279288

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1448181.3311638744 1337971.22197854...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16298  17690  85305  Maricopa         08  14485.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.54804298199943, -112.25319169854255)

                                 best_width       link  \
0  (33.54804298199943, -112.25319169854255)  923.03857

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1493395.4749762022 1292762.84960567...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16299  17691  85305  Maricopa         09  14485.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.526484439954565, -112.25613181388844)

               best_width         link  \
0  (33.52996, -112.25563)  3069.287523

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  MULTIPOLYGON (((-1493919.4955684145 1290691.25...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16300  17692  85042  Maricopa         04  45315.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.31812185913896, -112.07712824608129)

                                 best_width         link  \
0  (33.31812185913896, -112.07712824608129)  1399.174522

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1477393.1367253044 1264027.26011820...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16301  17693  85042  Maricopa         03  45315.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.36373753850554, -112.04637554834584)

               best_width         link  \
0  (33.35911, -112.04949)  3406.726789

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1480763.4070461602 1267882.50826697...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16302  17694  85201  Maricopa         04  53402.0  Arizona

  center_lat                                 lookup_lat  \
0         AZ  (33.427155930889796, -111.85219415338324)

              best_width         link  \
0  (33.4336, -111.84929)  2825.537148

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1460903.2282418467 1273943.04360351...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16303  17695  85201  Maricopa         01  53402.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.45030822925877, -111.84162906928232)

                                 best_width         link  \
0  (33.45030822925877, -111.84162906928232)  1544.917848

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1458906.7200031113 1274470.60001856...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16304  17696  85203  Maricopa         04  38719.0  Arizona

  center_lat                               lookup_lat              best_width  \
0         AZ  (33.43496491560955, -111.8037357403312)  (33.44997, -111.80403)

          link                                           geometry  \
0  2779.353964  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1454953.6241117904 1271315.70142947...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16305  17697  85203  Maricopa         01  38719.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.47051054024231, -111.80444157888847)

                                 best_width         link  \
0  (33.47051054024231, -111.80444157888847)  3043.772003

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1454320.7680023683 1274803.44573753...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16306  17698  85306  Maricopa         08  23598.0  Arizona

  center_lat                                lookup_lat  \
0         AZ  (33.62332109337312, -112.17569508977692)

               best_width         link  \
0  (33.62333, -112.17569)  2924.092636

                                            geometry  \
0  https://edbltn.github.io/show-me-the-ballot/da...

                                              latlng  \
0  POLYGON ((-1485614.481332484 1300241.442674235...

                                            response
0  {"success": true, "data": {"districts": [{"id"...
   intersection_id    zip county  district population    state state_id  \
0            16307  17699  85044  Maricopa         04  40815.0  Arizona

  center_lat                               lookup_lat              best_width  \

Processing rows:  42%|████████████████▏                      | 277/666 [00:02<00:03, 120.66it/s]

KeyboardInterrupt:

In [34]:
result_df.tail(30)

,0,response
9314,03,"{""success"": true, ""data"": {""districts"": [{""id""..."
9315,3149.0,"{""success"": true, ""data"": {""districts"": [{""id""..."
9316,Arizona,"{""success"": true, ""data"": {""districts"": [{""id""..."
9317,AZ,"{""success"": true, ""data"": {""districts"": [{""id""..."
9318,"(37.08954149721607, -110.74490281594383)","{""success"": true, ""data"": {""districts"": [{""id""..."
9319,"(37.08954149721607, -110.74490281594383)","{""success"": true, ""data"": {""districts"": [{""id""..."
9320,18269.919643,"{""success"": true, ""data"": {""districts"": [{""id""..."
9321,https://edbltn.github.io/show-me-the-ballot/da...,"{""success"": true, ""data"": {""districts"": [{""id""..."
9322,POLYGON ((-1271063.3975225189 1647583.68140929...,"{""success"": true, ""data"": {""districts"": [{""id""..."
9323,"(37.08954149721607, -110.74490281594383)","{""success"": true, ""data"": {""districts"": [{""id""..."

In [35]:
result_df

,0,response
0,7459,"{""success"": true, ""data"": {""districts"": [{""id""..."
1,8131,"{""success"": true, ""data"": {""districts"": [{""id""..."
2,85333,"{""success"": true, ""data"": {""districts"": [{""id""..."
3,Yuma,"{""success"": true, ""data"": {""districts"": [{""id""..."
4,09,"{""success"": true, ""data"": {""districts"": [{""id""..."
...,...,...
9319,"(37.08954149721607, -110.74490281594383)","{""success"": true, ""data"": {""districts"": [{""id""..."
9320,18269.919643,"{""success"": true, ""data"": {""districts"": [{""id""..."
9321,https://edbltn.github.io/show-me-the-ballot/da...,"{""success"": true, ""data"": {""districts"": [{""id""..."
9322,POLYGON ((-1271063.3975225189 1647583.68140929...,"{""success"": true, ""data"": {""districts"": [{""id""..."
9323,"(37.08954149721607, -110.74490281594383)","{""success"": true, ""data"": {""districts"": [{""id""..."

In [ ]:
#result_df.to_csv('data/2025/ariz_oct19.csv')